<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mime-info [
  <!ELEMENT mime-info (mime-type)+>
  <!ATTLIST mime-info xmlns CDATA #FIXED "http://www.freedesktop.org/standards/shared-mime-info">

  <!ELEMENT mime-type (comment|glob|magic|root-XML|alias|sub-class-of)*>
  <!ATTLIST mime-type type CDATA #REQUIRED>

  <!ELEMENT comment (#PCDATA)>
  <!ATTLIST comment xml:lang CDATA #IMPLIED>

  <!ELEMENT glob EMPTY>
  <!ATTLIST glob pattern CDATA #REQUIRED>

  <!ELEMENT magic (match)+>
  <!ATTLIST magic priority CDATA #IMPLIED>

  <!ELEMENT match (match)*>
  <!ATTLIST match offset CDATA #REQUIRED>
  <!ATTLIST match type (string|big16|big32|little16|little32|host16|host32|byte) #REQUIRED>
  <!ATTLIST match value CDATA #REQUIRED>
  <!ATTLIST match mask CDATA #IMPLIED>

  <!ELEMENT root-XML EMPTY>
  <!ATTLIST root-XML
  	namespaceURI CDATA #REQUIRED
	localName CDATA #REQUIRED>

  <!ELEMENT alias EMPTY>
  <!ATTLIST alias
  	type CDATA #REQUIRED>

  <!ELEMENT sub-class-of EMPTY>
  <!ATTLIST sub-class-of
  	type CDATA #REQUIRED>
]>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/andrew-inset">
    <comment>Andrew Toolkit inset</comment>
    <comment xml:lang="az">Andrew Toolkit sənədi</comment>
    <comment xml:lang="cs">Andrew Toolkit inset</comment>
    <comment xml:lang="cy">Mewnosodiad Andrew Toolkit</comment>
    <comment xml:lang="de">Andrew Toolkit-Inset</comment>
    <comment xml:lang="fi">Andrew Toolkit -osio</comment>
    <comment xml:lang="fr">ajout Andrew Toolkit</comment>
    <comment xml:lang="hu">Andrew Toolkit inset</comment>
    <comment xml:lang="ko">Andrew 툴킷 inset</comment>
    <comment xml:lang="nn">Andrew Toolkit innsats</comment>
    <comment xml:lang="no">Andrew verktøysett insett</comment>
    <comment xml:lang="sr">Andrew додатаг групе алата</comment>
    <comment xml:lang="sv">Andrew-verktygssamling insatt</comment>
    <glob pattern="*.ez"/>
  </mime-type>
  <mime-type type="application/illustrator">
    <comment>Adobe Illustrator document</comment>
    <comment xml:lang="de">Adobe Illustrator-Dokument</comment>
    <comment xml:lang="el">Έγγραφο Adobe Illustrator</comment>
    <comment xml:lang="fi">Adobe Illustrator -asiakirja</comment>
    <comment xml:lang="no">Adobe Illustrator-dokument</comment>
    <comment xml:lang="sv">Adobe Illustrator-dokument</comment>
    <glob pattern="*.ai"/>
  </mime-type>
  <mime-type type="application/mac-binhex40">
    <comment>Macintosh BinHex-encoded file</comment>
    <comment xml:lang="az">Macintosh BinHex-kodlanmış fayl</comment>
    <comment xml:lang="cs">Soubor kódovaný Macintosh BinHex</comment>
    <comment xml:lang="cy">Ffeil BinHex-amgodwyd Macintosh</comment>
    <comment xml:lang="de">Macintosh-Datei (BinHex-kodiert)</comment>
    <comment xml:lang="el">Αρχείο Macintosh κωδικοποίησης BinHex</comment>
    <comment xml:lang="fi">Macintosh BinHex -koodattu tiedosto</comment>
    <comment xml:lang="fr">fichier encode Macintosh BinHex</comment>
    <comment xml:lang="hu">Macintosh BinHex kódolású fájl</comment>
    <comment xml:lang="ko">맥킨토시 BinHex-encoded 압축파일</comment>
    <comment xml:lang="nl">Macintosh BinHex-gecodeerd bestand</comment>
    <comment xml:lang="nn">Macintosh BinHex-koda fil</comment>
    <comment xml:lang="no">Macintosh BinHe-kodet arkiv</comment>
    <comment xml:lang="sr">Мекинтош BinHex-encoded датотека</comment>
    <comment xml:lang="sv">Macintosh BinHex-kodad fil</comment>
    <magic priority="50">
      <match value="must be converted with BinHex" type="string" offset="11"/>
    </magic>
  </mime-type>
  <mime-type type="application/octet-stream">
    <comment>unknown</comment>
    <comment xml:lang="de">unbekannt</comment>
    <comment xml:lang="el">άγνωστο</comment>
    <comment xml:lang="fi">tuntematon</comment>
    <comment xml:lang="no">ukjent</comment>
    <magic priority="50">
      <match value="\037\036" type="string" offset="0"/>
      <match value="017437" type="host16" offset="0"/>
      <match value="0x1fff" type="host16" offset="0"/>
      <match value="\377\037" type="string" offset="0"/>
      <match value="0145405" type="host16" offset="0"/>
    </magic>
    <glob pattern="*.bin"/>
  </mime-type>
  <mime-type type="application/oda">
    <comment>ODA document</comment>
    <comment xml:lang="az">ODA sənədi</comment>
    <comment xml:lang="cs">Dokument ODA</comment>
    <comment xml:lang="cy">Dogfen ODA</comment>
    <comment xml:lang="de">ODA-Dokument</comment>
    <comment xml:lang="el">Έγγραφο ODA</comment>
    <comment xml:lang="fi">ODA-asiakirja</comment>
    <comment xml:lang="fr">document ODA</comment>
    <comment xml:lang="hu">ODA-dokumentum</comment>
    <comment xml:lang="ko">ODA 문서</comment>
    <comment xml:lang="nl">ODA document</comment>
    <comment xml:lang="nn">ODA-dokument</comment>
    <comment xml:lang="no">ODA-dokument</comment>
    <comment xml:lang="sr">ODA документ</comment>
    <comment xml:lang="sv">ODA-dokument</comment>
    <glob pattern="*.oda"/>
  </mime-type>
  <mime-type type="application/pdf">
    <comment>PDF document</comment>
    <comment xml:lang="cy">Dogfen PDF</comment>
    <comment xml:lang="de">PDF-Dokument</comment>
    <comment xml:lang="el">Έγγραφο PDF</comment>
    <comment xml:lang="fi">PDF-asiakirja</comment>
    <comment xml:lang="nn">PDF-dokument</comment>
    <comment xml:lang="no">PDF-dokument</comment>
    <comment xml:lang="sr">PDF документ</comment>
    <comment xml:lang="sv">PDF-dokument</comment>
    <magic priority="50">
      <match value="%PDF-" type="string" offset="0"/>
    </magic>
    <glob pattern="*.pdf"/>
  </mime-type>
  <mime-type type="application/pgp">
    <comment>PGP message</comment>
    <comment xml:lang="az">PGP ismarışı</comment>
    <comment xml:lang="cs">Zpráva PGP</comment>
    <comment xml:lang="cy">Neges PGP</comment>
    <comment xml:lang="de">PGP-Nachricht</comment>
    <comment xml:lang="el">Μήνυμα PGP</comment>
    <comment xml:lang="fi">PGP-viesti</comment>
    <comment xml:lang="fr">message PGP</comment>
    <comment xml:lang="hu">PGP-üzenet</comment>
    <comment xml:lang="ko">PGP 메세지</comment>
    <comment xml:lang="nl">PGP bericht</comment>
    <comment xml:lang="nn">PGP-melding</comment>
    <comment xml:lang="no">PGP-melding</comment>
    <comment xml:lang="sr">PGP порука</comment>
    <comment xml:lang="sv">PGP-meddelande</comment>
    <glob pattern="*.pgp"/>
  </mime-type>
  <mime-type type="application/pgp-encrypted">
    <comment>PGP/MIME-encrypted message header</comment>
    <comment xml:lang="de">PGP/MIME-verschlüsselter Nachrichtenkopf</comment>
    <comment xml:lang="fi">PGP/MIME-salattu viestiotsikko</comment>
    <comment xml:lang="no">PGP/MIME-kryptert meldingshode</comment>
  </mime-type>
  <mime-type type="application/pgp-keys">
    <comment>PGP keys</comment>
    <comment xml:lang="az">PGP açarları</comment>
    <comment xml:lang="cs">Klíče PGP</comment>
    <comment xml:lang="cy">Allweddi PGP</comment>
    <comment xml:lang="de">PGP-Schlüssel</comment>
    <comment xml:lang="el">Κλειδιά PGP</comment>
    <comment xml:lang="fi">PGP-avainrengas</comment>
    <comment xml:lang="fr">clés PGP</comment>
    <comment xml:lang="hu">PGP-kulcs</comment>
    <comment xml:lang="ko">PGP 키</comment>
    <comment xml:lang="nl">PGP sleutels</comment>
    <comment xml:lang="nn">PGP-nøkler</comment>
    <comment xml:lang="no">PGP-nøkler</comment>
    <comment xml:lang="sr">PGP кључ</comment>
    <comment xml:lang="sv">PGP-nycklar</comment>
  </mime-type>
  <mime-type type="application/pgp-signature">
    <comment>detached OpenPGP signature</comment>
    <comment xml:lang="de">isolierte OpenPGP-Signatur</comment>
    <comment xml:lang="fi">erillinen OpenPGP-allekirjoitus</comment>
    <comment xml:lang="no">frakoblet OpenPGP-signatur</comment>
  </mime-type>
  <mime-type type="application/pkcs7-mime">
    <comment>S/MIME file</comment>
    <comment xml:lang="az">S/MIME faylı</comment>
    <comment xml:lang="cs">Soubor S/MIME</comment>
    <comment xml:lang="cy">Ffeil S/MIME</comment>
    <comment xml:lang="de">S/MIME-Datei</comment>
    <comment xml:lang="el">Αρχείο S/MIME</comment>
    <comment xml:lang="fi">S/MIME-tiedosto</comment>
    <comment xml:lang="fr">fichier S/MIME</comment>
    <comment xml:lang="hu">S/MIME-fájl</comment>
    <comment xml:lang="ko">S/MIME 파일</comment>
    <comment xml:lang="nl">S/MIME bestand</comment>
    <comment xml:lang="nn">S/MIME-fil</comment>
    <comment xml:lang="no">S/MIME-fil</comment>
    <comment xml:lang="sr">S/MIME датотека</comment>
    <comment xml:lang="sv">S/MIME-fil</comment>
  </mime-type>
  <mime-type type="application/pkcs7-signature">
    <comment>detached S/MIME signature</comment>
    <comment xml:lang="de">isolierte S/MIME-Signatur</comment>
    <comment xml:lang="fi">erillinen S/MIME-allekirjoitus</comment>
    <comment xml:lang="no">frakoblet S/MIME-signatur</comment>
    <glob pattern="*.p7s"/>
  </mime-type>
  <mime-type type="application/postscript">
    <comment>PostScript document</comment>
    <comment xml:lang="de">PostScript-Dokument</comment>
    <comment xml:lang="el">Έγγραφο PostScript</comment>
    <comment xml:lang="fi">PostScript-asiakirja</comment>
    <comment xml:lang="no">PostScript-dokument</comment>
    <comment xml:lang="sv">PostScript-dokument</comment>
    <magic priority="50">
      <match value="\004%!" type="string" offset="0"/>
      <match value="%!" type="string" offset="0"/>
    </magic>
    <glob pattern="*.ps"/>
  </mime-type>
  <mime-type type="application/rtf">
    <sub-class-of type="text/plain"/>
    <comment>Rich Text Format</comment>
    <comment xml:lang="az">Zəngin Mətn Formatı</comment>
    <comment xml:lang="cs">Rich Text Format</comment>
    <comment xml:lang="cy">Dogfen Testun Gyfoethog</comment>
    <comment xml:lang="de">Richt-Text-Format</comment>
    <comment xml:lang="fi">RTF-asiakirja</comment>
    <comment xml:lang="fr">Rich Text Format</comment>
    <comment xml:lang="hu">RTF-fájl</comment>
    <comment xml:lang="ko">Rich Text 형식</comment>
    <comment xml:lang="nl">Rijke Tekst Formaat</comment>
    <comment xml:lang="nn">Rik tekst-dokument</comment>
    <comment xml:lang="no">Rik tekst-format</comment>
    <comment xml:lang="sr">Обогаћени текстуални запис (RTF)</comment>
    <comment xml:lang="sv">Rikt textdokument</comment>
    <magic priority="50">
      <match value="{\\rtf" type="string" offset="0"/>
    </magic>
    <glob pattern="*.rtf"/>
  </mime-type>
  <mime-type type="application/smil">
    <sub-class-of type="text/plain"/>
    <comment>Synchronized Multimedia Integration Language</comment>
    <comment xml:lang="az">Sinxronlaşdırılmış Multemediya İnteqrasiya Dili</comment>
    <comment xml:lang="cs">Synchronized Multimedia Integration Language</comment>
    <comment xml:lang="cy">Iaith Integreiddio Aml-Gyfrwng wedi ei Chydweddu</comment>
    <comment xml:lang="de">SMIL-Dokument</comment>
    <comment xml:lang="fi">Synchronized Multimedia Integration Language</comment>
    <comment xml:lang="fr">Synchronized Multimedia Integration Language</comment>
    <comment xml:lang="hu">Szinkronizált multimédiaintegrációs nyelv</comment>
    <comment xml:lang="ko">동기화 멀티미디어 통합 언어</comment>
    <comment xml:lang="nl">Gesynchroniseerde multimedia integratie taal</comment>
    <comment xml:lang="nn">Synchronized Multimedia Integration Language</comment>
    <comment xml:lang="sr">Синхронизовани језик за интеграцију мултимедије (SMIL)</comment>
    <comment xml:lang="sv">Språk för synkroniserad multimediaintegration</comment>
    <glob pattern="*.smil"/>
    <glob pattern="*.smi"/>
    <glob pattern="*.sml"/>
  </mime-type>
  <mime-type type="application/vnd.corel-draw">
    <comment>Corel Draw drawing</comment>
    <comment xml:lang="az">Corel Draw çəkimi</comment>
    <comment xml:lang="cs">Kresba Corel Draw</comment>
    <comment xml:lang="cy">Darlun Corel Draw</comment>
    <comment xml:lang="de">Corel Draw-Zeichnung</comment>
    <comment xml:lang="el">Σχέδιο Corel Draw </comment>
    <comment xml:lang="fi">Corel Draw -piirros</comment>
    <comment xml:lang="fr">dessin Corel Draw</comment>
    <comment xml:lang="hu">Corel Draw-rajz</comment>
    <comment xml:lang="ko">코렐 드로우 드로잉</comment>
    <comment xml:lang="nl">Corel Draw tekening</comment>
    <comment xml:lang="nn">Corel Draw-teikning</comment>
    <comment xml:lang="no">Corel Draw-tegning</comment>
    <comment xml:lang="sr">Corel Draw цртеж</comment>
    <comment xml:lang="sv">Corel Draw-teckning</comment>
    <magic priority="50">
      <match value="CDR vrsn" type="string" offset="8"/>
    </magic>
    <glob pattern="*.cdr"/>
  </mime-type>
  <mime-type type="application/vnd.hp-hpgl">
    <comment>HP Graphics Language (plotter)</comment>
    <comment xml:lang="de">HP-Grafiksprache (Plotter)</comment>
    <comment xml:lang="fi">HP Graphics Language (piirturi)</comment>
    <glob pattern="*.hpgl"/>
  </mime-type>
  <mime-type type="application/vnd.hp-pcl">
    <comment>HP Printer Control Language file</comment>
    <comment xml:lang="de">HP-Druckersteuerungs-Sprachdatei</comment>
    <comment xml:lang="fi">HP Printer Control Language -tiedosto</comment>
    <glob pattern="*.pcl"/>
  </mime-type>
  <mime-type type="application/vnd.lotus-1-2-3">
    <comment>Lotus 1-2-3 spreadsheet</comment>
    <comment xml:lang="az">Lotus 1-2-3 hesab cədvəli</comment>
    <comment xml:lang="cs">Tabulka Lotus 1-2-3</comment>
    <comment xml:lang="cy">Taenlen Lotus 1-2-3</comment>
    <comment xml:lang="de">Lotus 1-2-3-Tabellendokument</comment>
    <comment xml:lang="el">Λογιστικό φύλλο Lotus 1-2-3</comment>
    <comment xml:lang="fi">Lotus 1-2-3 -taulukko</comment>
    <comment xml:lang="fr">chiffrier Lotus 1-2-3</comment>
    <comment xml:lang="hu">Lotus 1-2-3-munkafüzet</comment>
    <comment xml:lang="ko">Lotus 1-2-3 스프레드시트</comment>
    <comment xml:lang="nl">Lotus 1-2-3 spreadsheet</comment>
    <comment xml:lang="nn">Lotus 1-2-3 rekneark</comment>
    <comment xml:lang="no">Lotus 1-2-3 regneark</comment>
    <comment xml:lang="sr">Lotus 1-2-3 табеларни прорачун</comment>
    <comment xml:lang="sv">Lotus 1-2-3-kalkylblad</comment>
    <magic priority="50">
      <match value="\x00\x00\x02\x00" type="string" offset="0"/>
    </magic>
    <glob pattern="*.123"/>
    <glob pattern="*.wk1"/>
    <glob pattern="*.wk3"/>
    <glob pattern="*.wk4"/>
    <glob pattern="*.wks"/>
  </mime-type>
  <mime-type type="application/vnd.ms-excel">
    <comment>Microsoft Excel spreadsheet</comment>
    <comment xml:lang="az">Microsoft Excel hesab cədvəli</comment>
    <comment xml:lang="cs">Tabulka Microsoft Excel</comment>
    <comment xml:lang="cy">Taenlen Microsoft Excel</comment>
    <comment xml:lang="de">Microsoft Excel-Tabellendokument</comment>
    <comment xml:lang="el">Λογιστικό φύλλο Microsoft Excel</comment>
    <comment xml:lang="fi">Microsoft Excel -taulukko</comment>
    <comment xml:lang="fr">chiffrier Microsoft Excel</comment>
    <comment xml:lang="hu">Microsoft Excel-munkafüzet</comment>
    <comment xml:lang="ko">마이크로소프트 엑셀 스프레드시트</comment>
    <comment xml:lang="nl">Microsoft Excel spreadsheet</comment>
    <comment xml:lang="nn">Microsoft Excel reikneark</comment>
    <comment xml:lang="no">Microsoft Excel regneark</comment>
    <comment xml:lang="sr">Микрософт Ексел табеларни прорачун</comment>
    <comment xml:lang="sv">Microsoft Excel-kalkylblad</comment>
    <magic priority="50">
      <match value="Microsoft Excel 5.0 Worksheet" type="string" offset="2080"/>
    </magic>
    <glob pattern="*.xls"/>
    <glob pattern="*.xlc"/>
    <glob pattern="*.xll"/>
    <glob pattern="*.xlm"/>
    <glob pattern="*.xlw"/>
    <glob pattern="*.xla"/>
    <glob pattern="*.xlt"/>
    <glob pattern="*.xld"/>
    <alias type="application/msexcel"/>
  </mime-type>
  <mime-type type="application/vnd.ms-powerpoint">
    <comment>Microsoft PowerPoint presentation</comment>
    <comment xml:lang="de">Microsoft PowerPoint-Präsentation</comment>
    <comment xml:lang="el">Παρουσίαση Microsoft PowerPoint</comment>
    <comment xml:lang="fi">Microsoft PowerPoint -esitys</comment>
    <comment xml:lang="no">Microsoft PowerPoint-presentasjon</comment>
    <glob pattern="*.ppz"/>
    <glob pattern="*.ppt"/>
    <glob pattern="*.pps"/>
    <glob pattern="*.pot"/>
    <magic priority="50">
      <match value="0xcfd0e011" type="little32" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/vnd.ms-word">
    <comment>Microsoft Word document</comment>
    <comment xml:lang="az">Microsoft Word sənədi</comment>
    <comment xml:lang="cs">Dokument Microsoft Word</comment>
    <comment xml:lang="cy">Dogfen Miscrosoft Word</comment>
    <comment xml:lang="de">Microsoft Word-Dokument</comment>
    <comment xml:lang="el">Έγγραφο Microsoft Word</comment>
    <comment xml:lang="fi">Microsoft Word -asiakirja</comment>
    <comment xml:lang="fr">document Microsoft Word</comment>
    <comment xml:lang="hu">Microsoft Word-dokumentum</comment>
    <comment xml:lang="ko">마이크로소프트 워드 문서</comment>
    <comment xml:lang="nl">Microsoft Word document</comment>
    <comment xml:lang="nn">Microsoft Word-dokument</comment>
    <comment xml:lang="no">Microsoft Word dokument</comment>
    <comment xml:lang="sr">Микрософт Word документ</comment>
    <comment xml:lang="sv">Microsoft Word-dokument</comment>
    <magic priority="50">
      <match value="\x31\xbe\x00\x00" type="string" offset="0"/>
      <match value="PO^Q`" type="string" offset="0"/>
      <match value="\376\067\0\043" type="string" offset="0"/>
      <match value="\333\245-\0\0\0" type="string" offset="0"/>
      <match value="Microsoft Word 6.0 Document" type="string" offset="2080"/>
      <match value="Microsoft Word document data" type="string" offset="2112"/>
    </magic>
    <glob pattern="*.doc"/>
    <alias type="application/msword"/>
  </mime-type>
  <mime-type type="application/vnd.palm">
    <comment>Palmpilot database/document</comment>
    <comment xml:lang="de">Palmpilot-Datenbank/-Dokument</comment>
    <comment xml:lang="fi">Palmpilot-tietokanta tai -asiakirja</comment>
    <glob pattern="*.pdb"/>
  </mime-type>
  <mime-type type="application/vnd.rn-realmedia">
    <comment>RealAudio/Video document</comment>
    <comment xml:lang="az">RealAudio/Video sənədi</comment>
    <comment xml:lang="cs">Dokument RealAudio/Video</comment>
    <comment xml:lang="cy">Dogfen RealAudio neu RealVideo</comment>
    <comment xml:lang="de">RealAudio/Video-Dokument</comment>
    <comment xml:lang="el">Έγγραφο RealAudio/Video</comment>
    <comment xml:lang="fi">RealAudio/Video-asiakirja</comment>
    <comment xml:lang="fr">document RealAudio/Video</comment>
    <comment xml:lang="hu">RealAudio/Video-dokumentum</comment>
    <comment xml:lang="ko">리얼오디오/비디오 문서</comment>
    <comment xml:lang="nl">RealAudio/Video document</comment>
    <comment xml:lang="nn">RealAudio/Video-dokument</comment>
    <comment xml:lang="no">RealAudio/Video-dokument</comment>
    <comment xml:lang="sr">RealAudio/Video документ</comment>
    <comment xml:lang="sv">RealAudio/Video-dokument</comment>
  </mime-type>
  <mime-type type="application/vnd.stardivision.calc">
    <comment>StarCalc spreadsheet</comment>
    <comment xml:lang="az">StarCalc hesab cədvəli</comment>
    <comment xml:lang="cs">Tabulka StarCalc</comment>
    <comment xml:lang="cy">Taenlen StarCalc</comment>
    <comment xml:lang="de">StarCalc-Tabellendokument</comment>
    <comment xml:lang="el">Λογιστικό φύλλο StarCalc</comment>
    <comment xml:lang="fi">StarCalc-taulukko</comment>
    <comment xml:lang="fr">chiffier StarCalc</comment>
    <comment xml:lang="hu">StarCalc-munkafüzet</comment>
    <comment xml:lang="ko">StarCalc 스프레드시트</comment>
    <comment xml:lang="nl">StarCalc spreadsheet</comment>
    <comment xml:lang="nn">StarCalc-rekneark</comment>
    <comment xml:lang="no">StarCalc-regneark</comment>
    <comment xml:lang="sr">StarCalc табеларни прорачун</comment>
    <comment xml:lang="sv">StarCalc-kalkylblad</comment>
    <glob pattern="*.sdc"/>
  </mime-type>
  <mime-type type="application/vnd.stardivision.chart">
    <comment>StarChart chart</comment>
    <comment xml:lang="az">StarChart cədvəli</comment>
    <comment xml:lang="cs">Graf StarChart</comment>
    <comment xml:lang="cy">Siart StarChart</comment>
    <comment xml:lang="de">StarChart-Diagramm</comment>
    <comment xml:lang="el">Γράφημα StarChart</comment>
    <comment xml:lang="fi">StarChart-kaavio</comment>
    <comment xml:lang="fr">graphique StarChart</comment>
    <comment xml:lang="hu">StarChart-grafikon</comment>
    <comment xml:lang="ko">StarCalc 표</comment>
    <comment xml:lang="nl">StarChart grafiek</comment>
    <comment xml:lang="nn">StarChart-graf</comment>
    <comment xml:lang="no">StarChart graf</comment>
    <comment xml:lang="sr">StarChart графикон</comment>
    <comment xml:lang="sv">StarChart-diagram</comment>
    <glob pattern="*.sds"/>
  </mime-type>
  <mime-type type="application/vnd.stardivision.draw">
    <comment>StarDraw drawing</comment>
    <comment xml:lang="az">StarDraw çəkimi</comment>
    <comment xml:lang="cs">Kresba StarDraw</comment>
    <comment xml:lang="cy">Darlun StarDraw</comment>
    <comment xml:lang="de">StarDraw-Zeichnung</comment>
    <comment xml:lang="el">Σχέδιο StarDraw</comment>
    <comment xml:lang="fi">StarDraw-piirros</comment>
    <comment xml:lang="fr">dessin StarDraw</comment>
    <comment xml:lang="hu">StarDraw-rajz</comment>
    <comment xml:lang="ko">StarCalc 드로잉</comment>
    <comment xml:lang="nl">StarDraw tekening</comment>
    <comment xml:lang="nn">StarDraw-teikning</comment>
    <comment xml:lang="no">StarDraw tegning</comment>
    <comment xml:lang="sr">StarDraw drawing</comment>
    <comment xml:lang="sv">StarDraw-teckning</comment>
    <glob pattern="*.sda"/>
  </mime-type>
  <mime-type type="application/vnd.stardivision.impress">
    <comment>StarImpress presentation</comment>
    <comment xml:lang="az">StarImpress təqdimatı</comment>
    <comment xml:lang="cs">Prezentace StarImpress</comment>
    <comment xml:lang="cy">Cyflwyniad StarImpress</comment>
    <comment xml:lang="de">StarImpress-Präsentation</comment>
    <comment xml:lang="el">Παρουσίαση StarImpress</comment>
    <comment xml:lang="fi">StarImpress-esitys</comment>
    <comment xml:lang="fr">présentation StarImpress</comment>
    <comment xml:lang="hu">StarImpress-bemutató</comment>
    <comment xml:lang="ko">StarImpress 프리젠테이션</comment>
    <comment xml:lang="nl">StarImpress presentatie</comment>
    <comment xml:lang="nn">StarImpress-presentasjon</comment>
    <comment xml:lang="no">StarImpress-presentasjon</comment>
    <comment xml:lang="sr">StarImpress презентација</comment>
    <comment xml:lang="sv">StarImpress-presentation</comment>
    <glob pattern="*.sdd"/>
    <glob pattern="*.sdp"/>
  </mime-type>
  <mime-type type="application/vnd.stardivision.mail">
    <comment>StarMail email</comment>
    <comment xml:lang="de">StarMail-E-Mail</comment>
    <comment xml:lang="fi">StarMail-tiedosto</comment>
    <comment xml:lang="no">StarMail-melding</comment>
    <glob pattern="*.smd"/>
  </mime-type>
  <mime-type type="application/vnd.stardivision.math">
    <comment>StarMath formula</comment>
    <comment xml:lang="de">StarMath-Formel</comment>
    <comment xml:lang="fi">StarMath-asiakirja</comment>
    <comment xml:lang="no">StarMath-formel</comment>
    <glob pattern="*.smf"/>
  </mime-type>
  <mime-type type="application/vnd.stardivision.writer">
    <comment>StarWriter document</comment>
    <comment xml:lang="az">StarWriter sənədi</comment>
    <comment xml:lang="cs">Dokument StarWriter</comment>
    <comment xml:lang="cy">Dogfen StarWriter</comment>
    <comment xml:lang="de">StarWriter-Dokument</comment>
    <comment xml:lang="el">Έγγραφο StarWriter</comment>
    <comment xml:lang="fi">StarWriter-asiakirja</comment>
    <comment xml:lang="fr">document StarWriter</comment>
    <comment xml:lang="hu">StarWriter-dokumentum</comment>
    <comment xml:lang="ko">StarWriter 문서</comment>
    <comment xml:lang="nl">StarWriter document</comment>
    <comment xml:lang="nn">StarWriter document</comment>
    <comment xml:lang="no">StarWriter-dokument</comment>
    <comment xml:lang="sr">StarWriter документ</comment>
    <comment xml:lang="sv">StarWriter-dokument</comment>
    <glob pattern="*.sdw"/>
    <glob pattern="*.vor"/>
    <glob pattern="*.sgl"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.calc">
    <comment>OpenOffice.org Calc spreadsheet</comment>
    <comment xml:lang="de">OpenOffice.org Calc-Tabellendokumen</comment>
    <comment xml:lang="el">Λογιστικό φύλλο OpenOffice.org Calc</comment>
    <comment xml:lang="fi">OpenOffice.org Calc -taulukko</comment>
    <comment xml:lang="no">OpenOffice.org Calc-regneark</comment>
    <glob pattern="*.sxc"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.calc.template">
    <comment>OpenOffice.org Calc spreadsheet template</comment>
    <comment xml:lang="de">OpenOffice.org Calc-Vorlage für Tabellendokument</comment>
    <comment xml:lang="el">Πρότυπο λογιστικό φύλλο OpenOffice.org Calc</comment>
    <comment xml:lang="fi">OpenOffice.org Calc -taulukkomalli</comment>
    <comment xml:lang="no">OpenOffice.org Calc-regnearkmal</comment>
    <glob pattern="*.stc"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.draw">
    <comment>OpenOffice.org Draw drawing</comment>
    <comment xml:lang="de">OpenOffice.org Draw-Zeichnung</comment>
    <comment xml:lang="fi">OpenOffice.org-Draw -piirros</comment>
    <comment xml:lang="no">OpenOffice.org Draw-tegning</comment>
    <glob pattern="*.sxd"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.draw.template">
    <comment>OpenOffice.org Draw drawing template</comment>
    <comment xml:lang="de">OpenOffice.org·Draw-Zeichnungsvorlage</comment>
    <comment xml:lang="fi">OpenOffice.org Draw -piirrosmalli</comment>
    <comment xml:lang="no">OpenOffice.org Draw-tegningsmal</comment>
    <glob pattern="*.std"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.impress">
    <comment>OpenOffice.org Impress presentation</comment>
    <comment xml:lang="de">OpenOffice.org·Impress-Präsentation</comment>
    <comment xml:lang="el">Παρουσίαση OpenOffice.org Impress</comment>
    <comment xml:lang="fi">OpenOffice.org Impress -esitys</comment>
    <comment xml:lang="no">OpenOffice.org Impress-presentasjon</comment>
    <comment xml:lang="sv">OpenOffice.org Impress-presentation</comment>
    <glob pattern="*.sxi"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.impress.template">
    <comment>OpenOffice.org Impress presentation template</comment>
    <comment xml:lang="de">OpenOffice.org·Impress-Präsentationsvorlage</comment>
    <comment xml:lang="el">Πρότυπο Παρουσίασης OpenOffice.org Impress</comment>
    <comment xml:lang="fi">OpenOffice.org Impress -esitysmalli</comment>
    <comment xml:lang="no">OpenOffice.org Impress-presentasjonsmal</comment>
    <comment xml:lang="sv">OpenOffice.org Impress-presentationsmall</comment>
    <glob pattern="*.sti"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.math">
    <comment>OpenOffice.org Math formula</comment>
    <comment xml:lang="de">OpenOffice.org·Math-Formel</comment>
    <comment xml:lang="fi">OpenOffice.org Math-asiakirja</comment>
    <comment xml:lang="no">OpenOffice.org Math-dokument</comment>
    <glob pattern="*.sxm"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.writer">
    <comment>OpenOffice.org Writer document</comment>
    <comment xml:lang="de">OpenOffice.org·Writer-Dokument</comment>
    <comment xml:lang="el">Έγγραφο OpenOffice.org Writer</comment>
    <comment xml:lang="fi">OpenOffice.org Writer -asiakirja</comment>
    <comment xml:lang="no">OpenOffice.org Writer-dokument</comment>
    <comment xml:lang="sv">OpenOffice.org Writer-dokument</comment>
    <glob pattern="*.sxw"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.writer.global">
    <comment>OpenOffice.org Writer global document</comment>
    <comment xml:lang="de">OpenOffice.org·Writer-Globaldokument</comment>
    <comment xml:lang="fi">yleinen OpenOffice.org Write -asiakirja</comment>
    <comment xml:lang="no">Globalt OpenOffice.org Writer-dokument</comment>
    <comment xml:lang="sv">OpenOffice.org Writer-globaldokument</comment>
    <glob pattern="*.sxg"/>
  </mime-type>
  <mime-type type="application/vnd.sun.xml.writer.template">
    <comment>OpenOffice.org Writer document template</comment>
    <comment xml:lang="de">OpenOffice.org·Writer-Dokumentenvorlage</comment>
    <comment xml:lang="el">Πρότυπο έγγραφο OpenOffice.org Writer</comment>
    <comment xml:lang="fi">OpenOffice.org Writer -asiakirjamalli</comment>
    <comment xml:lang="no">OpenOffice.org Writer-dokumentmal</comment>
    <glob pattern="*.stw"/>
  </mime-type>
  <mime-type type="application/vnd.wordperfect">
    <alias type="application/x-wordperfect"/>
    <alias type="application/wordperfect"/>
    <comment>WordPerfect document</comment>
    <comment xml:lang="az">WordPerfect sənədi</comment>
    <comment xml:lang="cs">Dokument WordPerfect</comment>
    <comment xml:lang="cy">Dogfen WordPerfect</comment>
    <comment xml:lang="de">WordPerfect-Dokument</comment>
    <comment xml:lang="el">Έγγραφο WordPerfect</comment>
    <comment xml:lang="fi">WordPerfect-asiakirja</comment>
    <comment xml:lang="fr">document WordPerfect</comment>
    <comment xml:lang="hu">WordPerfect-dokumentum</comment>
    <comment xml:lang="ko">워드퍼펙트 문서</comment>
    <comment xml:lang="nl">WordPerfect document</comment>
    <comment xml:lang="nn">WordPerfect-dokument</comment>
    <comment xml:lang="no">WordPerfect-dokument</comment>
    <comment xml:lang="sr">WordPerfect документ</comment>
    <comment xml:lang="sv">WordPerfect-dokument</comment>
    <magic priority="50">